sudo: false
language: python
python:
  - 3.7.5
  - pypy3
install:
  - pip install tox

script: 
  - pytest
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-cov41-pyyaml
